// Centralized mock data for buy properties
// Shared between buy listing and buy details pages

export const BUY_PROPERTIES = [
  {
    id: 1,
    image: '/buy-rent/fourbeds.webp',
    imageAlt: 'Modern villa with pool',
    location: 'Abidjan, Cocody',
    title: 'Modern 4-Bedroom Villa with Pool',
    priceXOF: 150000000,
    priceUSD: 250000,
    isVerified: true,
    propertyType: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    city: 'abidjan',
  },
  {
    id: 2,
    image: '/buy-rent/luxurypent.jpg',
    imageAlt: 'Luxury apartment',
    location: 'Abidjan, Plateau',
    title: 'Luxury Penthouse in Plateau',
    priceXOF: 200000000,
    priceUSD: 333000,
    isVerified: true,
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 280,
    city: 'abidjan',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    // separate image
    imageAlt: 'Elegant house',
    location: 'Yamoussoukro',
    title: 'Elegant 5-Bedroom House',
    priceXOF: 120000000,
    priceUSD: 200000,
    isVerified: true,
    propertyType: 'house',
    bedrooms: 5,
    bathrooms: 4,
    area: 420,
    city: 'yamoussoukro',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    // separate image
    imageAlt: 'Spacious family home',
    location: 'Abidjan, Marcory',
    title: 'Spacious Family Home in Marcory',
    priceXOF: 95000000,
    priceUSD: 158000,
    isVerified: false,
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 3,
    area: 320,
    city: 'abidjan',
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    // separate image
    imageAlt: 'Contemporary villa',
    location: 'Assinie-Mafia',
    title: 'Beachfront Villa in Assinie',
    priceXOF: 180000000,
    priceUSD: 300000,
    isVerified: true,
    propertyType: 'villa',
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    city: 'assinie',
  },
  {
    id: 6,
    image: '/buy-rent/threebeds.jpg',
    imageAlt: 'Modern apartment',
    location: 'Abidjan, Cocody',
    title: 'Modern 3-Bedroom Apartment',
    priceXOF: 85000000,
    priceUSD: 142000,
    isVerified: true,
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    city: 'abidjan',
  },
  {
    id: 7,
    image: '/buy-rent/tempo.png',
    imageAlt: 'Townhouse',
    location: 'Abidjan, Riviera',
    title: 'Contemporary Townhouse',
    priceXOF: 110000000,
    priceUSD: 183000,
    isVerified: true,
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 3,
    area: 300,
    city: 'abidjan',
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
    // separate image
    imageAlt: 'Garden villa',
    location: 'Yamoussoukro',
    title: 'Garden Villa with Pool',
    priceXOF: 98000000,
    priceUSD: 163000,
    isVerified: true,
    propertyType: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    area: 380,
    city: 'yamoussoukro',
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
    // separate image
    imageAlt: 'Executive apartment',
    location: 'Abidjan, Plateau',
    title: 'Executive Apartment Downtown',
    priceXOF: 140000000,
    priceUSD: 233000,
    isVerified: false,
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 160,
    city: 'abidjan',
  },
  {
    id: 10,
    image: '/buy-rent/luxury.png',
    imageAlt: 'Luxury penthouse',
    location: 'Abidjan, Cocody',
    title: 'Luxury Penthouse with City Views',
    priceXOF: 250000000,
    priceUSD: 417000,
    isVerified: true,
    propertyType: 'apartment',
    bedrooms: 4,
    bathrooms: 4,
    area: 350,
    city: 'abidjan',
  },
  {
    id: 11,
    image: '/buy-rent/withGarden.png',
    imageAlt: 'Modern house',
    location: 'Abidjan, Marcory',
    title: 'Modern House with Garden',
    priceXOF: 105000000,
    priceUSD: 175000,
    isVerified: true,
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 3,
    area: 310,
    city: 'abidjan',
  },
  {
    id: 12,
    image: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
    // separate image
    imageAlt: 'Coastal villa',
    location: 'Assinie-Mafia',
    title: 'Coastal Villa with Private Beach',
    priceXOF: 220000000,
    priceUSD: 367000,
    isVerified: true,
    propertyType: 'villa',
    bedrooms: 6,
    bathrooms: 5,
    area: 500,
    city: 'assinie',
  },
];

export const getBuyPropertyById = (id) =>
  BUY_PROPERTIES.find((p) => String(p.id) === String(id));
